#!/usr/bin/env bash
# Downloads all staff photos from Google Drive CDN into assets/people/
# Run once from the repo root: bash download-staff-photos.sh

set -e
DEST="assets/people"
mkdir -p "$DEST"

download() {
  local id="$1" name="$2"
  local file="$DEST/$name"
  if [ -f "$file" ]; then
    echo "✓ exists   $name"
  else
    echo "↓ fetching $name"
    curl -fsSL -o "$file" "https://lh3.googleusercontent.com/d/$id" || echo "  ✗ failed  $name"
  fi
}

download "12B50ktYeAUaShjg1MiCpkEY_i6m87_u-" "pichey-ken.jpg"
download "13s_ak2EWgSoodkQIU3mj2DymHIi11-4H"  "noya-men.jpg"
download "15BY-cz7g5l4XdJ5OaQrQBkaXU-72UPJV"  "sophea-mak.jpg"
download "16o9p2Z6bynHvhG63wF2PGEQpSm0LD_Yk"  "phin-teb.jpg"
download "17bG8bScaHC-TJUFP4GkULVGjycrtC23Z"  "kolap-touch.jpg"
download "18VtEdGxrvoe8J3T6oj_TYrNp11qZJPAn"  "nan-houn.jpg"
download "19QElIeBNWAqOQMHl9iJz8uZygTwPtYzy"  "seav-ey-khean.jpg"
download "1Ckxmav7FZlQw5WNOcQO7PUxYLlEIo4hs"  "sopheak-vat.jpg"
download "1Cl2iVURyFvE0KfYtpd0IsHVGuC9b_r8V"  "makara-seng.jpg"
download "1CpzDpqo-N2-qCSUcN9Da4tx8jIsr-NUA"  "sreymom-lim.jpg"
download "1DLdPqfTMQCfZ7IGt1qDz5HR-ukixPPoE"  "ousaphea-lim.jpg"
download "1E9Xl3TlsgJRSYpL4pdEYdYmV1Xprd7jb"  "barang-soeurm.jpg"
download "1EiMr3Hs4yMwtCTBaQPzGYGR2v4_TfqHI"  "sreyleak-orn.jpg"
download "1FEfUzck7LZcOAHJUVRU_SwTgR37qpdq9"  "lieng-huon.jpg"
download "1FKIoSuWY2xvqmT_Xpt2Yjt3p1gJX8fVf"  "sreymom-touch.jpg"
download "1F_DuiMORuPeP8bRF3u-FJns1ks40v8mX"  "hean-luos.jpg"
download "1ItwZaVIVHjR0VtcTZQTBSNuEweGGO670"  "sophy-chek.jpg"
download "1KcZeGH2mkuAKzlCaI7vS4xTDM2tiO8S6"  "sreyleak-so.jpg"
download "1Kg8bRlHgVSJp_EkVxxLoQ2wRNfGvI8yW"  "ryna-mom.jpg"
download "1KYLYV74PsaUU2rXoVzgpodcrfGIUQnr7"  "vicheth-song.jpg"
download "1LMor1p6PlXsBY4tEEM3obdpJsneN3YLX"  "sreypeou-hout.jpg"
download "1Lm0pWKXWWjEHs4OcKgrptcAVRztjCSXf"  "khemry-men.jpg"
download "1NO2qMy91mby7VOKpZ--PDprVsGDjQHbI"  "kanha-un.jpg"
download "1OpBRDDXjDL6gONS-sx6hDsA48W_x6lwT"  "sreymom-thorng.jpg"
download "1PaobujykuEoMV1jyIIjeaZX1nED9FqUK"  "rina-nov.jpg"
download "1PpiMAxMDmLGjD66rC3DiEY5RcCmCwHc3"  "chrach-chen.jpg"
download "1PtKbDH0fTBw32FcI14wFYVe-TcVeVsj6"  "sopheap-heang.jpg"
download "1RRCB0n_L5xJD8L4l-7bV-v4IhnWSTKaL"  "chamroeun-muon.jpg"
download "1Ryqt_yfBD6Wm5pTu-oWlKrZbD8tBIc-o"  "sopheap-ngat.jpg"
download "1SMi7h7TWKyHNCfubW1peOK9yS1AFHK58"  "su-sey.jpg"
download "1T3YGRTVpRbs0H1LC-s2l5Anbewx56ovU"  "panha-neang.jpg"
download "1T5PsmIWlR-wD4yRPjPlK9y7lQAsZdEp3"  "sambath-song.jpg"
download "1U3o2ytDZMEtJHvwkUQ82y-OSG_YiYnum"  "sovansreyreach-tat.jpg"
download "1UyovW4_W1qZW4v3mbNAOINo9jc6gkzR9"  "seyla-nga.jpg"
download "1YtvZLyqBhNF-PqOP_wMpJjmfvrRqSWPl"  "sreypich-chhean.jpg"
download "1_Z6rt4eP2F69dr-VNCH8mfCOuikOz5OK"  "boromey-hom.jpg"
download "1_uXFwzOPjKKG3AhD79qTEZRN1r2eoA7F"  "kim-sopheap.jpg"
download "1cBIZEvAhQjIuDAXVrsxt0fefz3EOQMSI"  "tola-khem.jpg"
download "1cQp0oCmvWmtYYFfA9fdJhS3qsP6YUv-x"  "sengly-muol.jpg"
download "1fd75gzxxBfmTiTbb9Km1cn4Xg6bjzOgZ"  "mom-kalic.jpg"
download "1fyR6y3nBtXKy9SfwdRRAA_cAg06EQCZz"  "savry-klot.jpg"
download "1gzrWox_6_t45ak8oPhoFBEOdPVzoz1XG"  "jane-meas.jpg"
download "1herP04RX_uIUvFCi5pOtEGjjy3uLoaz4"  "seangly-leng.jpg"
download "1iEbb8-9-r213z3AMgI3cr7wvlfvvBOXV"  "rin-nga.jpg"
download "1iHmbtDH9nM0aHB-wiQ9yz11qcxNTeCUG"  "kongkea-kouk.jpg"
download "1ivaGknObKl9Db7zwfLxGf3h74OkYKWkp"  "sreileak-rous.jpg"
download "1kEDvMfan-xJPTJmwyp00cFUavrMJW-ZP"  "champa-toch.jpg"
download "1kH7H9xvH8HJLpwOPb3bm-H5jp7VKnKkt"  "sila-kun.jpg"
download "1lwnSCHbwJ2l9n4V53nwGMrkR3izbH_VK"  "rothana-ros.jpg"
download "1rO2Qd4WTGFRP6GWnH2w5s8hh6D0p2ABy"  "sotheany-ngeun.jpg"
download "1sgf52Xl1LTgzntqtb0XIaGsqYnnidZ6i"  "sokuntheary-sim.jpg"
download "1uPuo4OjupoKrLsqTtgsFojhIi6G77a6D"  "kim-sorn-soeuth.jpg"
download "1vih05SeCfwzEwDcvD7_AVNPsXwca_U9F"  "sombo-ros.jpg"
download "1wrU8qFUqfujc4287Ovuz-id7bs826jIB"  "srytom-pogn.jpg"
download "1xXxQM4x8eRw6s-XZWSIIXizwq4aefY3o"  "hin-loeb.jpg"
download "1ypQbxtmFqJjtvROE24XPOSu7ViInuCkI"  "ya-hoeun.jpg"
download "1zOJxLOsVVAtz9DiTKp9PZjUP3RtevtBF"  "srey-roth-outh.jpg"
download "1zbPyv1efgVCvHz9p6pnauH23BJLvcRlZ"  "matthew-seng.jpg"

echo ""
echo "Done! $(ls $DEST/*.jpg 2>/dev/null | wc -l) photos in $DEST/"
